- name: Setting up database
  vars_files:
    - ./setting.yml
  become: true
  hosts: database
  roles:
    - docker
    - db
- name: Setting up server
  vars_files:
    - ./setting.yml
  become: true
  hosts: server
  roles:
    - docker
    - server