---
# tasks file for db
- name: Create /ansible/ directory
  file:
    path: /ansible
    state: directory

- name: Clone vnlab-training-yii
  git:
    repo: https://github.com/minhhnn-vnlab/yii-application.git
    dest: /ansible/
    clone: yes
    update: yes

- name: Copy .env file
  template:
    src: .env.j2
    dest: /ansible/.env

- name: Building Docker containers for database
  command: docker compose -f /ansible/docker-compose.yml build database

- name: Composing up Database in Docker
  command: docker compose -f /ansible/docker-compose.yml up -d database

- name: Seeding database
  command: docker exec postgres psql -U {{ database.postgres_username }} -d {{ database.postgres_db }} -f /data/seed.sql
